# -*- coding: utf-8 -*-
"""Box_office_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7VKh1rilS5PpZywlq5YVad_2Jq88p48
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.the-numbers.com/box-office-chart/weekend/2024/07/05"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

tables = soup.find_all("table")
target_table = tables[1]

rows = target_table.find_all("tr")
data = []
for row in rows[1:]:
    cols = [col.text.strip() for col in row.find_all("td")]
    if cols:
        data.append(cols)

headers = [
    "Rank", "Previous Rank", "Movie Title", "Distributor",
    "Gross", "% LW", "Theaters", "Change", "Per Theater",
    "Total Gross", "Week"
]

df = pd.DataFrame(data, columns=headers)
df.to_csv("box_office_data.csv", index=False)

df.head()